### ISSUE TITLE
Support for PPP without authentication

### ISSUE THREAD

**Issue by nward** [rtbrick/bngblaster#259]
**Is your feature request related to a problem? Please describe.**

Some BNG configurations don't request PPP authentication, and relying on agent-circuit-id and agent-remote-id.
BNG blaster does not operate if authentication is not configured. If it is configured, but not negotiated, it does not bring up the session and just constantly tries to request authentication to be negotiated.

**Describe the solution you'd like**

Two options, maybe both:
- Support client configurations which do not have authentication
- Allow clients to come up when a BNG does not negotiate authentication

**Describe alternatives you've considered**

We can change the BNG configuration in some cases to use a default username/password - however this is a functional change to the BNG so is not ideal for testing.

**Additional context**

n/a

**Comment by GIC-de** [comment]
I haven't expected this use case, since all customer I worked with using line based authentication (agent-remote-id, ...), they just ignore username/password but still negotiate authentication. 

The main reason for ignoring authentication vs. disabled authentication is the better client compatibility, since some clients did not support PPPoE without authentication. Another reason for authentication is that a lot of providers pass some CPE parameters like shaping rate, ... using the authentication reply-message. 

Anyhow, I can consider this as an option to disable authentication in the BNG Blaster.

**Comment by GIC-de** [comment]
Fixed in `dev` branch. As long as there is no authentication protocol explicitly configured in the BNG Blaster configuration, we will now accept to skip authentication phase.

**Comment by GIC-de** [comment]
This change is now available in version 0.9.3!
