### ISSUE TITLE
Configuration of IPV6CP interface identifier

### ISSUE THREAD

**Issue by JohnMiller7** [rtbrick/bngblaster#64]
Hello,

Is there any way to influence or configure the PPP IPv6 Interface identifier of BNG Blaster, which is negotiated during IPV6CP?
In my tests, the interface identifier seems to be always 00:00:00:00:00:00:00:00 for all sessions. Maybe the interface identifier could be based on the session number?

Regards,
John

**Comment by GIC-de** [comment]
This issue is fixed in latest `dev`!
https://github.com/rtbrick/bngblaster/actions/runs/1663181428

Now the IP6CP interface identifier is derived from unique client MAC address using EUI-64: 
![image](https://user-images.githubusercontent.com/6083768/148391938-864d4fc9-1d4d-48de-94bb-53dbfc85d88c.png)

Please verify and close if fix is working for you!

**Comment by JohnMiller7** [comment]
Thanks a lot! This works great for me.
