### ISSUE TITLE
BNG Blaster not responding to PADO

### ISSUE THREAD

**Issue by hazeyb** [rtbrick/bngblaster#73]
**Describe the bug**

**To Reproduce**

Running on Ubuntu 20.04.4,  installed version is bngblaster-0.7.1-ubuntu-20.04_amd64.deb

Version (`bngblaster -v`):

```
Version: 0.7.1
IO Modes: packet_mmap_raw (default), packet_mmap, raw
```

JSON configuration:
```json
{
    "interfaces": {
	"qdisc-bypass": false,
        "io-mode": "packet_mmap_raw",
        "access": [
            {
                "interface": "enp3s0f0",
                "type": "pppoe",
		"outer-vlan-min": 4,
                "outer-vlan-max": 4,
                "inner-vlan-min": 1,
                "inner-vlan-max": 4094,
                "authentication-protocol": "CHAP"
            }
        ]
    },
    "sessions": {
        "count": 10,
        "session-time": 0,
        "max-outstanding": 800,
        "start-rate": 400,
        "stop-rate": 400
    },
    "pppoe": {
        "reconnect": true,
        "discovery-timeout": 10,
        "discovery-retry": 10
    },
    "ppp": {
        "mru": 1492,
        "authentication": {
            "username": "mx10k3test{session-global}@zen",
            "password": "password",
            "timeout": 5,
            "retry": 30,
	    "protocol": "CHAP"
        },
        "lcp": {
            "conf-request-timeout": 1,
            "conf-request-retry": 10,
            "keepalive-interval": 30,
            "keepalive-retry": 3
        },
        "ipcp": {
            "enable": true,
            "request-ip": true,
            "request-dns1": true,
            "request-dns2": true,
            "conf-request-timeout": 1,
            "conf-request-retry": 10
        },
        "ip6cp": {
            "enable": true,
            "conf-request-timeout": 1,
            "conf-request-retry": 10
        }
    },
    "dhcpv6": {
        "enable": true,
        "rapid-commit": true
    },
    "access-line": {
        "agent-remote-id": "DEU.RTBRICK.{session-global}",
        "agent-circuit-id": "0.0.0.0/0.0.0.0 eth 0:{session-global}",
        "rate-up": 1024,
        "rate-down": 16384
    }
}
```

1.   start BNG using "sudo bngblaster -C pppoe.json"

**Expected behavior**

I'd expect a PADR to be created.  I do note that the PADI is double tagged on the PCAP, but the PADO appears single tagged, when PCAP'd using BNGBlaster,  but when running the capture on the Arista switch (upstream from the server), the tagging is as expected

**Arista PCAP**

20:36:02.409429 02:00:00:00:00:01 > Broadcast, ethertype 802.1Q (0x8100), length 92: vlan 4, p 0, ethertype 802.1Q, vlan 1, p 0, ethertype PPPoE D, PPPoE PADI [Service-Name] [Vendor-Specific "......0.0.0.0/0.0.0.0 eth 0:1..DEU.RTBRICK.1..........@."]

20:36:02.477526 f2:7c:c7:af:77:f3 > 02:00:00:00:00:01, ethertype 802.1Q (0x8100), length 76: vlan 4, p 6, ethertype 802.1Q, vlan 1, p 6, ethertype PPPoE D, PPPoE PADO [AC-Name "BNG3.THN-LON.LAB-RE0"] [Service-Name] [AC-Cookie "G~...9.{t. ..7]c"]

20:36:07.414196 02:00:00:00:00:01 > f2:7c:c7:af:77:f3, ethertype 802.1Q (0x8100), length 92: vlan 4, p 0, ethertype 802.1Q, vlan 1, p 0, ethertype PPPoE D, PPPoE PADI [Service-Name] [Vendor-Specific "......0.0.0.0/0.0.0.0 eth 0:1..DEU.RTBRICK.1..........@."]

**Comment by GIC-de** [comment]
The outer VLAN is often not captured as explained in the FAQ:
https://rtbrick.github.io/bngblaster/faq.html

_Some interface drivers drop the outer VLAN header. The BNG Blaster tries to recover the VLAN from kernel headers but will not change the packets stored in the PCAP file._

You can start BNG Blaster with `-l pppoe -l debug -L test.log` to get more details but I guess I know the issue. 

By default, the BNG Blaster send's an empty service-name TAG. This means to accept any service from the BNG. But the BNG Blaster always expects to include a service name in the PADO from the BNG. 

The RFC is not concrete about how to handle empty service-name tags. In our own BNG implementation, we respond with service-name `access` if PADI does not include a service-name otherwise, we respond with the service-name from PADI. This showed us the best compatibility with the different client implementations and CPE devices. 

You can send a service-name from BNG Blaster with the following configuration to get your setup up and running.
```
{
    "pppoe": {
        "service-name": "access"
    }
}
```

Actually, it's the second time seeing this bug, so will think about changing the default behavior of BNG Blaster to send a service name per default or accept an empty service name in the PADO.

**Comment by hazeyb** [comment]
Hi,

Setting the service name worked. 

Normally we use a Spirent for testing our BNGs. The Spirent also sends empty service-name TAG by default, and our BNG (Juniper MX10K3) responds with the PADO without a service name. (We have the BNG set to permit any service).   The Spirent accepts an empty service name in the PADO.

**Comment by GIC-de** [comment]
I will address this in the next release.

**Comment by hazeyb** [comment]
Thank you, will get that tested today.

**Comment by hazeyb** [comment]
All working.  Thank you .
